### ISSUE TITLE
How to restrict the size of perturbations

### ISSUE THREAD

**Issue by yuxinWen** [ytsmiling/lmt#3]
Table 1 in your paper shows the performance of your work under different size of the perturbations. However, I'm confused how to restrict the size of perturbations especially under optimized based attack, i.e C&W attack. And it seems that there are no suggestions in your code. Could you please show how can I optimize adversarial examples under max_epsilon? Thanks a lot!

**Comment by ytsmiling** [comment]
In C&W attack, the attack tries to find the minimal size perturbations. We counted that a pair of model and input is robust against perturbations smaller than one when the found smallest perturbation had a size larger than one.

**Comment by yuxinWen** [comment]
Got it, thanks!
