### ISSUE TITLE
The Lipschitz constant in pooling layer

### ISSUE THREAD

**Issue by sungyoon-lee** [ytsmiling/lmt#5]
@ytsmiling 
In the code pooling.py, you multiply 'factor' to l.
https://github.com/ytsmiling/lmt/blob/31e36e54d858fbc0a1f2eab12d5a86a97284339f/src/function/pooling.py#L23
I am confused because some papers said "the max-pooling layer has a Lipschitz constant equal to 1",  for example, https://papers.nips.cc/paper/7640-lipschitz-regularity-of-deep-neural-networks-analysis-and-efficient-estimation.pdf.

However, I think the Lipschitz constant is not supposed to be 1.
Could you explain it more explicitly or provide me a reference?

**Comment by ytsmiling** [comment]
When kernel size and stride does not match, the Lipschitz constant is not necessarily one.

Let's consider a 1d max-pooling example.
Input: [1,2,1,2,1]
kernel size: 2
stride: 1
padding: nothing
Output: [2, 2, 2, 2]
|Output|/|Input| > 1

**Comment by sungyoon-lee** [comment]
Thank you!
